### ISSUE TITLE
libmolgrid seems incompatible with dlab_re_vs_pipeline

### ISSUE THREAD

**Issue by hui2000ji** [con-schneider/dlab-public#1]
Hi DLAB developers, thanks for your great work!
I am trying to run your code following the given README and using the provided example inputs. The data preparation part went well (I didn't block the non-interaction-site atoms but I think that's fine). However when I run dlab_re_vs_pipeline.py, I get the following error:
```
Traceback (most recent call last):
  File "dlab_re_vs_pipeline.py", line 405, in <module>
    run(config_dict)
  File "dlab_re_vs_pipeline.py", line 392, in run
    results.append([target_dir.name, run_on_docking_folder(target_dir, config)])
  File "dlab_re_vs_pipeline.py", line 365, in run_on_docking_folder
    dlab_re_df = run_dlab_re(folder, config)
  File "dlab_re_vs_pipeline.py", line 279, in run_dlab_re
    gmaker.forward(
Boost.Python.ArgumentError: Python argument types in
    GridMaker.forward(GridMaker, Example, Tensor)
did not match C++ signature:
    forward(libmolgrid::GridMaker {lvalue}, libmolgrid::Grid<float, 2ul, true>, libmolgrid::Grid<float, 3ul, true>, libmolgrid::Grid<float, 3ul, true>, libmolgrid::Grid<float, 2ul, true>, libmolgrid::Grid<float, 5ul, true>)
    forward(libmolgrid::GridMaker {lvalue}, libmolgrid::Grid<float, 2ul, false>, libmolgrid::Grid<float, 3ul, false>, libmolgrid::Grid<float, 3ul, false>, libmolgrid::Grid<float, 2ul, false>, libmolgrid::Grid<float, 5ul, false>)
    forward(libmolgrid::GridMaker {lvalue}, libmolgrid::Grid<float, 2ul, true>, libmolgrid::Grid<float, 3ul, true>, libmolgrid::Grid<float, 2ul, true>, libmolgrid::Grid<float, 2ul, true>, libmolgrid::Grid<float, 5ul, true>)
    forward(libmolgrid::GridMaker {lvalue}, libmolgrid::Grid<float, 2ul, false>, libmolgrid::Grid<float, 3ul, false>, libmolgrid::Grid<float, 2ul, false>, libmolgrid::Grid<float, 2ul, false>, libmolgrid::Grid<float, 5ul, false>)
    forward(libmolgrid::GridMaker {lvalue}, float3, libmolgrid::Grid<float, 2ul, true>, libmolgrid::Grid<float, 2ul, true>, libmolgrid::Grid<float, 1ul, true>, libmolgrid::Grid<float, 4ul, true>)
    forward(libmolgrid::GridMaker {lvalue}, float3, libmolgrid::Grid<float, 2ul, false>, libmolgrid::Grid<float, 2ul, false>, libmolgrid::Grid<float, 1ul, false>, libmolgrid::Grid<float, 4ul, false>)
    forward(libmolgrid::GridMaker {lvalue}, float3, libmolgrid::Grid<float, 2ul, true>, libmolgrid::Grid<float, 1ul, true>, libmolgrid::Grid<float, 1ul, true>, libmolgrid::Grid<float, 4ul, true> {lvalue})
    forward(libmolgrid::GridMaker {lvalue}, float3, libmolgrid::Grid<float, 2ul, false>, libmolgrid::Grid<float, 1ul, false>, libmolgrid::Grid<float, 1ul, false>, libmolgrid::Grid<float, 4ul, false> {lvalue})
    forward(libmolgrid::GridMaker {lvalue}, libmolgrid::Example, libmolgrid::Transform, libmolgrid::Grid<float, 4ul, true>)
    forward(libmolgrid::GridMaker {lvalue}, libmolgrid::Example, libmolgrid::Transform, libmolgrid::Grid<float, 4ul, false>)
    forward(libmolgrid::GridMaker {lvalue}, float3, libmolgrid::CoordinateSet, libmolgrid::Grid<float, 4ul, true>)
    forward(libmolgrid::GridMaker {lvalue}, float3, libmolgrid::CoordinateSet, libmolgrid::Grid<float, 4ul, false>)
    forward(libmolgrid::GridMaker {lvalue}, std::vector<libmolgrid::Example, std::allocator<libmolgrid::Example> > examples, libmolgrid::Grid<float, 5ul, true> grid, float random_translation=0.0, bool random_rotation=False)
    forward(libmolgrid::GridMaker {lvalue}, std::vector<libmolgrid::Example, std::allocator<libmolgrid::Example> > examplevec, libmolgrid::Grid<float, 5ul, false> grid, float random_translation=0.0, bool random_rotation=False)
    forward(libmolgrid::GridMaker {lvalue}, libmolgrid::Example example, libmolgrid::Grid<float, 4ul, true> grid, float random_translation=0.0, bool random_rotation=False)
    forward(libmolgrid::GridMaker {lvalue}, libmolgrid::Example example, libmolgrid::Grid<float, 4ul, false> grid, float random_translation=0.0, bool random_rotation=False)
```
I tried to modify the code of `dlab_re_vs_pipeline.py` to match the last C++ signature, `forward(libmolgrid::GridMaker {lvalue}, libmolgrid::Example example, libmolgrid::Grid<float, 4ul, false> grid, float random_translation=0.0, bool random_rotation=False)`. Specifically, I changed
```python
for j in range(bs):
    ex = batch[j]
    gmaker.forward(
        ex,
        batch_tensor[j],,
        random_translation=0.0,
        random_rotation=False,
        center=(0.0, 0.0, 0.0),
)
```
into
```python
for j in range(bs):
    ex = batch[j]
    gmaker.forward(
        ex,
        molgrid.tensor_as_grid(batch_tensor[j]),
        random_translation=0.0,
        random_rotation=False,
        center=(0.0, 0.0, 0.0),
)
```
However, the error persists:
```
Boost.Python.ArgumentError: Python argument types in
    GridMaker.forward(GridMaker, Example, Grid4fCUDA)
did not match C++ signature:
[Omitted]
```

I suspect this is due to some inconsistencies between the libmolgrid code and the dlab_re_vs_pipeline script. Could you look into it? Thank you very much!

FYI, I have already modified `ex_provider.type_size()` to `ex_provider.num_types()` in lines 123, 129, 136, 248, 258 to get the script running, before I bumped into the above error.

**Comment by hui2000ji** [comment]
Not sure if it's correct, but I tried
```python
for j in range(bs):
    ex = batch[j]
    gmaker.forward(
        ex,
        molgrid.Transform(
            center=molgrid.float3(0.0, 0.0, 0.0),
            random_translate=0.0,
            random_rotation=False
        ),
        molgrid.tensor_as_grid(batch_tensor[j])
    )
```
and now the code runs.

**Comment by purplerainf** [comment]
I thought I had a similar problem. It's a bit old issue, but I'd like to write some information and hopefully it may help someone.

As you know, DLAB uses its own modified libmolgrid so it calls another form of GridMaker::Forward function that is not included in the original libmolgrid library. 

In my case, **the original (unmodified) libmolgrid was also installed** via pip install command, then the error was occurred because the DLAB trys to find the functions from the original libmolgrid library. 

So the error was removed when I **uninstalled the original libmolgrid** via pip uninstall command.
